### ISSUE TITLE
Sonar Gerrit plugin aborted after load sonar report.

### ISSUE THREAD

**Issue by reda-alaoui** [jenkinsci/sonar-gerrit-plugin#47]
<p>Recently we met this issue several times that Sonar Gerrit Plugin failed to post report on Gerrit.</p>

<p>Here are the logs from Jenkins job & SonarToGerrit Logger:</p>
<blockquote>
<p> Getting Sonar Report from: /****/target/sonar/sonar-report.json</p>

<p>Report has loaded and contains 28 issues</p></blockquote>
<p> <br/>
Jun 23, 2020 1:20:54 PM SEVERE org.jenkinsci.plugins.sonargerrit.SonarToGerritPublisher perform</p>
<blockquote><p>Unable to post review: Request failed. java.net.SocketTimeoutException: Read timed out at java.net.SocketInputStream.socketRead0(Native Method) at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) at java.net.SocketInputStream.read(SocketInputStream.java:171) at java.net.SocketInputStream.read(SocketInputStream.java:141) at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) at sun.security.ssl.InputRecord.read(InputRecord.java:503) at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975) at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933) at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) at com.urswolfer.gerrit.client.rest.http.HttpRequestExecutor.execute(HttpRequestExecutor.java:34) at com.urswolfer.gerrit.client.rest.http.GerritRestClient.request(GerritRestClient.java:219) at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestRest(GerritRestClient.java:163) at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestRest(GerritRestClient.java:155) at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestJson(GerritRestClient.java:132)</p>

<p>Caused: com.google.gerrit.extensions.restapi.RestApiException: Request failed. at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestJson(GerritRestClient.java:147) at com.urswolfer.gerrit.client.rest.http.GerritRestClient.getRequest(GerritRestClient.java:101) at com.urswolfer.gerrit.client.rest.http.changes.FileApiRestClient.diff(FileApiRestClient.java:115) at com.urswolfer.gerrit.client.rest.http.changes.FileApiRestClient.access$200(FileApiRestClient.java:39) at com.urswolfer.gerrit.client.rest.http.changes.FileApiRestClient$2.get(FileApiRestClient.java:89) at com.urswolfer.gerrit.client.rest.http.changes.FileApiRestClient.diff(FileApiRestClient.java:76) at org.jenkinsci.plugins.sonargerrit.review.GerritRevisionWrapper.getChangedLinesByFile(GerritRevisionWrapper.java:75) at org.jenkinsci.plugins.sonargerrit.review.GerritRevisionWrapper.calculateFile2ChangedLines(GerritRevisionWrapper.java:68) at org.jenkinsci.plugins.sonargerrit.review.GerritRevisionWrapper.loadData(GerritRevisionWrapper.java:39) at org.jenkinsci.plugins.sonargerrit.SonarToGerritPublisher.perform(SonarToGerritPublisher.java:118) at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80) at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67) at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)</p></blockquote>
<i>[JENKINS-62781] created by gracesheep</i>

**Comment by reda-alaoui** [comment]
This is probably caused by the Gerrit instance.

**Comment by Incognito357** [comment]
I have run into this exact exception as well, and the Gerrit logs do not seem to indicate any issues on that side. The exception only occurs for me when I make a commit in Gerrit that contains large file changes (between 35-40 files each ~1MB with ~3.5k line modifications). Even if I ignore those files in the SonarQube scan explicitly (even though they don't fall under an extension that's scanned anyway), so this plugin doesn't need to publish any comments on those files (or at all), the plugin still throws this exception. If this is truly an issue on Gerrit's side, then I would not expect the Jenkins build to be able to publish a -1 score when this exception occurs, if this plugin is throwing an exception when trying to publish a +1 score.

Maybe the plugin just needs to increase the timeout, because Gerrit is processing the large files more slowly than normal, but doesn't actually fail, then the plugin terminates early instead of waiting. I'm not sure why Gerrit might be doing some kind of processing on the large files when the report this plugin sends shouldn't concern those files to begin with (unless the plugin is sending more than just the report, which causes Gerrit to do that?)

This issue is the only reference to this exception I can find, so hopefully this additional information can help provide some insight into the source of the problem, and we can figure out how to resolve it.

**Comment by reda-alaoui** [comment]
Related issue => https://github.com/uwolfer/gerrit-rest-java-client/issues/66

We use the plugin massively with huge Gerrit hosted repositories, we never had this issue.

Honestly, this root of this kind of issue can only be found by you. There are a million reasons why the connection could fail and I am not going to explore them. If you think it's a read timeout issue, maybe try to use a patched version of the plugin that sets an extended timeout on https://github.com/uwolfer/gerrit-rest-java-client to confirm the hypothesis.

**Comment by Incognito357** [comment]
The issue you linked is similar, but their problem was not being able to get the plugin to work at all, whereas my issue only fails in the scenario I mentioned above. I didn't realize this plugin was using the gerrit-rest-java-client plugin to do the communication, so that narrows down where I can look for the issue, so thanks for pointing me in the right direction.
